//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 09:36:41 PM CET 
//


package com.enonic.wem.api.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class XmlModuleElem
    extends JAXBElement<XmlModule>
{

    protected final static QName NAME = new QName("", "module");

    public XmlModuleElem(XmlModule value) {
        super(NAME, ((Class) XmlModule.class), null, value);
    }

    public XmlModuleElem() {
        super(NAME, ((Class) XmlModule.class), null, null);
    }

}
