//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.wem.api.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationshipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="from-semantic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="to-semantic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowed-from-types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="content-type" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allowed-to-types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="content-type" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipType", propOrder = {
    "description",
    "fromSemantic",
    "toSemantic",
    "allowedFromTypes",
    "allowedToTypes"
})
public class XmlRelationshipType {

    protected String description;
    @XmlElement(name = "from-semantic")
    protected String fromSemantic;
    @XmlElement(name = "to-semantic")
    protected String toSemantic;
    @XmlElement(name = "allowed-from-types")
    protected XmlRelationshipType.AllowedFromTypes allowedFromTypes;
    @XmlElement(name = "allowed-to-types")
    protected XmlRelationshipType.AllowedToTypes allowedToTypes;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fromSemantic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromSemantic() {
        return fromSemantic;
    }

    /**
     * Sets the value of the fromSemantic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromSemantic(String value) {
        this.fromSemantic = value;
    }

    /**
     * Gets the value of the toSemantic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToSemantic() {
        return toSemantic;
    }

    /**
     * Sets the value of the toSemantic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToSemantic(String value) {
        this.toSemantic = value;
    }

    /**
     * Gets the value of the allowedFromTypes property.
     * 
     * @return
     *     possible object is
     *     {@link XmlRelationshipType.AllowedFromTypes }
     *     
     */
    public XmlRelationshipType.AllowedFromTypes getAllowedFromTypes() {
        return allowedFromTypes;
    }

    /**
     * Sets the value of the allowedFromTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlRelationshipType.AllowedFromTypes }
     *     
     */
    public void setAllowedFromTypes(XmlRelationshipType.AllowedFromTypes value) {
        this.allowedFromTypes = value;
    }

    /**
     * Gets the value of the allowedToTypes property.
     * 
     * @return
     *     possible object is
     *     {@link XmlRelationshipType.AllowedToTypes }
     *     
     */
    public XmlRelationshipType.AllowedToTypes getAllowedToTypes() {
        return allowedToTypes;
    }

    /**
     * Sets the value of the allowedToTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlRelationshipType.AllowedToTypes }
     *     
     */
    public void setAllowedToTypes(XmlRelationshipType.AllowedToTypes value) {
        this.allowedToTypes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="content-type" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentType"
    })
    public static class AllowedFromTypes {

        @XmlElement(name = "content-type")
        protected List<String> contentType;

        /**
         * Gets the value of the contentType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getContentType() {
            if (contentType == null) {
                contentType = new ArrayList<String>();
            }
            return this.contentType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="content-type" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentType"
    })
    public static class AllowedToTypes {

        @XmlElement(name = "content-type")
        protected List<String> contentType;

        /**
         * Gets the value of the contentType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getContentType() {
            if (contentType == null) {
                contentType = new ArrayList<String>();
            }
            return this.contentType;
        }

    }

}
