language: java
sudo: false

jdk:
- oraclejdk8

install: true
script:
  - ./gradlew ci

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - oracle-java8-installer

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./misc/upload.sh
