///<reference path='ModuleTreeGrid.ts'/>
///<reference path='StartModuleAction.ts' />
///<reference path='StopModuleAction.ts' />
///<reference path='ModuleBrowseActions.ts' />
///<reference path='StopModuleEvent.ts' />
///<reference path='StartModuleEvent.ts' />
///<reference path='ModuleBrowseItemsSelectionPanel.ts' />
///<reference path='ModuleBrowsePanel.ts' />
///<reference path='ModuleBrowseToolbar.ts' />
///<reference path='ModuleBrowseItemPanel.ts'/>
