///<reference path="MixinName.ts" />
///<reference path="Mixin.ts" />
///<reference path="MixinResourceRequest.ts"/>
///<reference path="CreateMixinRequest.ts"/>
///<reference path="UpdateMixinRequest.ts"/>
///<reference path="DeleteMixinRequest.ts"/>
///<reference path="GetMixinConfigResult.ts"/>
///<reference path="GetMixinConfigByNameRequest.ts"/>
///<reference path="GetMixinByQualifiedNameRequest.ts"/>