///<reference path="Permission.ts"/>
///<reference path="PermissionHelper.ts"/>
///<reference path="AccessControlEntryJson.ts"/>
///<reference path="AccessControlEntry.ts"/>
///<reference path='AccessControlEntryLoader.ts' />
///<reference path="AccessControlList.ts"/>
///<reference path="Access.ts"/>
///<reference path="UserStoreAccess.ts"/>
///<reference path="UserStoreAccessControlEntryJson.ts"/>
///<reference path="UserStoreAccessControlEntry.ts"/>
///<reference path="UserStoreAccessControlList.ts"/>
///<reference path="UserStoreAccessControlEntryLoader.ts"/>