dependencies {
    implementation project( ':core:core-api' )
    implementation project( ':core:core-internal' )
    implementation libs.im4j
    testImplementation "com.enonic.im4j:im4j-natives-${gradle.ext.im4jHostPlatform()}:${libs.versions.im4j.get()}"
    implementation libs.jhlabs.filters
}

jar {
    bundle {
        bnd( 'Bundle-Name': 'Enonic XP Core - Image',
             'Private-Package': 'com.jhlabs.*' )
    }
}

tasks.withType( Test ).configureEach {
    testLogging.exceptionFormat = 'full'
}
