// @include plupload/js/moxie.min.js
// @include plupload/js/plupload.min.js
// @include jquery-2.1.4.js
// @include jquery-ui.js
// @include jquery.simulate.js
// @include jquery.slimscroll.min.js
// @include codemirror/codemirror.js
// @include codemirror/addon/loadmode.js
// @include signals.js
// @include hasher.js
// @include crossroads.js
// @include slickgrid/lib/jquery.event.drag-2.2.js
// @include slickgrid/lib/jquery.event.drop-2.2.js
// @include slickgrid/slick.core.js
// @include slickgrid/slick.grid.js
// @include slickgrid/slick.dataview.js
// @include slickgrid/slick.remotemodel.js
// @include slickgrid/slick.rowselectionmodel.js
// @include slickgrid/slick.checkboxselectcolumn.js
// @include slickgrid/slick.rowmovemanager.js
// @include mousetrap.js
// @include mousetrap-global-bind.min.js
// @include q.js
// @include noconflict.js
// @include tinymce/tinymce.js
// @include tinymce/themes/modern/theme.js
// @include tinymce/plugins/autoresize/plugin.js
// @include tinymce/plugins/table/plugin.js
// @include tinymce/plugins/paste/plugin.js
// @include tinymce/plugins/charmap/plugin.js
// @include tinymce/plugins/code/plugin.js
// @include bower_components/webcomponentsjs/webcomponents-lite.min.js
