///<reference path='BaseUserEvent.ts'/>
///<reference path='UserTreeGridItem.ts'/>
///<reference path='UserTreeGridItemViewer.ts'/>
///<reference path='UserItemsTreeGrid.ts'/>
///<reference path='UserTreeGridActions.ts' />
///<reference path='UserBrowseItemsSelectionPanel.ts' />
///<reference path='UserBrowsePanel.ts' />
///<reference path='UserBrowseToolbar.ts' />
///<reference path='UserBrowseItemPanel.ts'/>
///<reference path='UpdatePrincipalEvent.ts'/>
///<reference path='EditPrincipalEvent.ts'/>
///<reference path='UserItemDeletePromptEvent.ts'/>
///<reference path='PrincipalDuplicatedEvent.ts'/>
///<reference path='PrincipalSynchronizedEvent.ts'/>
///<reference path='NewPrincipalEvent.ts'/>
