// @include ext/ext-all.js
// @include plupload/js/plupload.full.js
// @include jquery-2.0.2.js
// @include jquery-ui-1.10.3.custom.min.js
// @include jquery.ui.live-draggable.js
// @include jquery.simulate.js
// @include codemirror/codemirror.js
// @include codemirror/addon/loadmode.js
// @include signals.js
// @include hasher.js
// @include crossroads.js
// @include slickgrid/lib/jquery.event.drag-2.2.js
// @include slickgrid/lib/jquery.event.drop-2.2.js
// @include slickgrid/slick.core.js
// @include slickgrid/slick.grid.js
// @include slickgrid/slick.dataview.js
// @include slickgrid/slick.remotemodel.js
// @include slickgrid/slick.rowselectionmodel.js
// @include slickgrid/slick.checkboxselectcolumn.js
// @include mousetrap.min.js
