//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 06:36:54 PM CET 
//


package com.enonic.wem.api.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.enonic.wem.api.xml.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _Mixin_QNAME = new QName( "", "mixin" );

    private final static QName _LayoutComponent_QNAME = new QName( "", "layout-component" );

    private final static QName _PartComponent_QNAME = new QName( "", "part-component" );

    private final static QName _Node_QNAME = new QName( "", "node" );

    private final static QName _ImageComponent_QNAME = new QName( "", "image-component" );

    private final static QName _PageComponent_QNAME = new QName( "", "page-component" );

    private final static QName _Module_QNAME = new QName( "", "module" );

    private final static QName _ContentType_QNAME = new QName( "", "content-type" );

    private final static QName _RelationshipType_QNAME = new QName( "", "relationship-type" );

    private final static QName _MetadataSchema_QNAME = new QName( "", "metadata-schema" );

    private final static QName _XmlContentFilterAllow_QNAME = new QName( "", "allow" );

    private final static QName _XmlContentFilterDeny_QNAME = new QName( "", "deny" );

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enonic.wem.api.xml.model
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link XmlMixin }
     */
    public XmlMixin createXmlMixin()
    {
        return new XmlMixin();
    }

    /**
     * Create an instance of {@link XmlLayoutDescriptor }
     */
    public XmlLayoutDescriptor createXmlLayoutDescriptor()
    {
        return new XmlLayoutDescriptor();
    }

    /**
     * Create an instance of {@link XmlPartDescriptor }
     */
    public XmlPartDescriptor createXmlPartDescriptor()
    {
        return new XmlPartDescriptor();
    }

    /**
     * Create an instance of {@link XmlNode }
     */
    public XmlNode createXmlNode()
    {
        return new XmlNode();
    }

    /**
     * Create an instance of {@link XmlImageDescriptor }
     */
    public XmlImageDescriptor createXmlImageDescriptor()
    {
        return new XmlImageDescriptor();
    }

    /**
     * Create an instance of {@link XmlPageDescriptor }
     */
    public XmlPageDescriptor createXmlPageDescriptor()
    {
        return new XmlPageDescriptor();
    }

    /**
     * Create an instance of {@link XmlModule }
     */
    public XmlModule createXmlModule()
    {
        return new XmlModule();
    }

    /**
     * Create an instance of {@link XmlContentType }
     */
    public XmlContentType createXmlContentType()
    {
        return new XmlContentType();
    }

    /**
     * Create an instance of {@link XmlRelationshipType }
     */
    public XmlRelationshipType createXmlRelationshipType()
    {
        return new XmlRelationshipType();
    }

    /**
     * Create an instance of {@link XmlMetadataSchema }
     */
    public XmlMetadataSchema createXmlMetadataSchema()
    {
        return new XmlMetadataSchema();
    }

    /**
     * Create an instance of {@link XmlFormItemSet }
     */
    public XmlFormItemSet createXmlFormItemSet()
    {
        return new XmlFormItemSet();
    }

    /**
     * Create an instance of {@link XmlRegionDescriptor }
     */
    public XmlRegionDescriptor createXmlRegionDescriptor()
    {
        return new XmlRegionDescriptor();
    }

    /**
     * Create an instance of {@link XmlPageRegions }
     */
    public XmlPageRegions createXmlPageRegions()
    {
        return new XmlPageRegions();
    }

    /**
     * Create an instance of {@link XmlPageRegion }
     */
    public XmlPageRegion createXmlPageRegion()
    {
        return new XmlPageRegion();
    }

    /**
     * Create an instance of {@link XmlPartComponent }
     */
    public XmlPartComponent createXmlPartComponent()
    {
        return new XmlPartComponent();
    }

    /**
     * Create an instance of {@link XmlMixinReference }
     */
    public XmlMixinReference createXmlMixinReference()
    {
        return new XmlMixinReference();
    }

    /**
     * Create an instance of {@link XmlVendor }
     */
    public XmlVendor createXmlVendor()
    {
        return new XmlVendor();
    }

    /**
     * Create an instance of {@link XmlDataSet }
     */
    public XmlDataSet createXmlDataSet()
    {
        return new XmlDataSet();
    }

    /**
     * Create an instance of {@link XmlFieldSet }
     */
    public XmlFieldSet createXmlFieldSet()
    {
        return new XmlFieldSet();
    }

    /**
     * Create an instance of {@link XmlInput }
     */
    public XmlInput createXmlInput()
    {
        return new XmlInput();
    }

    /**
     * Create an instance of {@link XmlFormItems }
     */
    public XmlFormItems createXmlFormItems()
    {
        return new XmlFormItems();
    }

    /**
     * Create an instance of {@link XmlDataProperty }
     */
    public XmlDataProperty createXmlDataProperty()
    {
        return new XmlDataProperty();
    }

    /**
     * Create an instance of {@link XmlMetadataSchemas }
     */
    public XmlMetadataSchemas createXmlMetadataSchemas()
    {
        return new XmlMetadataSchemas();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlMixin }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "mixin")
    public JAXBElement<XmlMixin> createMixin( XmlMixin value )
    {
        return new JAXBElement<XmlMixin>( _Mixin_QNAME, XmlMixin.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlLayoutDescriptor }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "layout-component")
    public JAXBElement<XmlLayoutDescriptor> createLayoutComponent( XmlLayoutDescriptor value )
    {
        return new JAXBElement<XmlLayoutDescriptor>( _LayoutComponent_QNAME, XmlLayoutDescriptor.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlPartDescriptor }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "part-component")
    public JAXBElement<XmlPartDescriptor> createPartComponent( XmlPartDescriptor value )
    {
        return new JAXBElement<XmlPartDescriptor>( _PartComponent_QNAME, XmlPartDescriptor.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlNode }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "node")
    public JAXBElement<XmlNode> createNode( XmlNode value )
    {
        return new JAXBElement<XmlNode>( _Node_QNAME, XmlNode.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlImageDescriptor }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "image-component")
    public JAXBElement<XmlImageDescriptor> createImageComponent( XmlImageDescriptor value )
    {
        return new JAXBElement<XmlImageDescriptor>( _ImageComponent_QNAME, XmlImageDescriptor.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlPageDescriptor }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "page-component")
    public JAXBElement<XmlPageDescriptor> createPageComponent( XmlPageDescriptor value )
    {
        return new JAXBElement<XmlPageDescriptor>( _PageComponent_QNAME, XmlPageDescriptor.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlModule }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "module")
    public JAXBElement<XmlModule> createModule( XmlModule value )
    {
        return new JAXBElement<XmlModule>( _Module_QNAME, XmlModule.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlContentType }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "content-type")
    public JAXBElement<XmlContentType> createContentType( XmlContentType value )
    {
        return new JAXBElement<XmlContentType>( _ContentType_QNAME, XmlContentType.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlRelationshipType }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "relationship-type")
    public JAXBElement<XmlRelationshipType> createRelationshipType( XmlRelationshipType value )
    {
        return new JAXBElement<XmlRelationshipType>( _RelationshipType_QNAME, XmlRelationshipType.class, null, value );
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link XmlMetadataSchema }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "metadata-schema")
    public JAXBElement<XmlMetadataSchema> createMetadataSchema( XmlMetadataSchema value )
    {
        return new JAXBElement<XmlMetadataSchema>( _MetadataSchema_QNAME, XmlMetadataSchema.class, null, value );
    }
}
