//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 06:36:54 PM CET 
//


package com.enonic.wem.api.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formItems complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formItems">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="input" type="{}input"/>
 *         &lt;element name="mixin-reference" type="{}mixinReference"/>
 *         &lt;element name="field-set" type="{}fieldSet"/>
 *         &lt;element name="form-item-set" type="{}formItemSet"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formItems", propOrder = {
    "items"
})
@XmlSeeAlso({
    XmlForm.class
})
public class XmlFormItems {

    @XmlElements({
        @XmlElement(name = "input", type = XmlInput.class),
        @XmlElement(name = "mixin-reference", type = XmlMixinReference.class),
        @XmlElement(name = "field-set", type = XmlFieldSet.class),
        @XmlElement(name = "form-item-set", type = XmlFormItemSet.class)
    })
    protected List<XmlFormItem> items;

    /**
     * Gets the value of the items property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the items property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlInput }
     * {@link XmlMixinReference }
     * {@link XmlFieldSet }
     * {@link XmlFormItemSet }
     * 
     * 
     */
    public List<XmlFormItem> getItems() {
        if (items == null) {
            items = new ArrayList<XmlFormItem>();
        }
        return this.items;
    }

}
