//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 06:36:54 PM CET 
//


package com.enonic.wem.api.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationshipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="from-semantic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="to-semantic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowed-from-types" type="{}allowedTypesDescriptor" minOccurs="0"/>
 *         &lt;element name="allowed-to-types" type="{}allowedTypesDescriptor" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipType", propOrder = {

})
public class XmlRelationshipType {

    protected String description;
    @XmlElement(name = "from-semantic")
    protected String fromSemantic;
    @XmlElement(name = "to-semantic")
    protected String toSemantic;
    @XmlElement(name = "allowed-from-types")
    protected XmlAllowedTypesDescriptor allowedFromTypes;
    @XmlElement(name = "allowed-to-types")
    protected XmlAllowedTypesDescriptor allowedToTypes;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fromSemantic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromSemantic() {
        return fromSemantic;
    }

    /**
     * Sets the value of the fromSemantic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromSemantic(String value) {
        this.fromSemantic = value;
    }

    /**
     * Gets the value of the toSemantic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToSemantic() {
        return toSemantic;
    }

    /**
     * Sets the value of the toSemantic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToSemantic(String value) {
        this.toSemantic = value;
    }

    /**
     * Gets the value of the allowedFromTypes property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAllowedTypesDescriptor }
     *     
     */
    public XmlAllowedTypesDescriptor getAllowedFromTypes() {
        return allowedFromTypes;
    }

    /**
     * Sets the value of the allowedFromTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAllowedTypesDescriptor }
     *     
     */
    public void setAllowedFromTypes(XmlAllowedTypesDescriptor value) {
        this.allowedFromTypes = value;
    }

    /**
     * Gets the value of the allowedToTypes property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAllowedTypesDescriptor }
     *     
     */
    public XmlAllowedTypesDescriptor getAllowedToTypes() {
        return allowedToTypes;
    }

    /**
     * Sets the value of the allowedToTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAllowedTypesDescriptor }
     *     
     */
    public void setAllowedToTypes(XmlAllowedTypesDescriptor value) {
        this.allowedToTypes = value;
    }

}
