///<reference path='ShowAppLauncherEvent.ts' />
///<reference path='ShowBrowsePanelEvent.ts' />
///<reference path='NamesView.ts'/>
///<reference path='NamesAndIconViewSize.ts'/>
///<reference path='NamesAndIconView.ts'/>
///<reference path='Application.ts'/>
///<reference path='AppLauncherEventType.ts' />
///<reference path='AppLauncherEvent.ts' />
///<reference path='AppPanel.ts' />
///<reference path='BrowseAndWizardBasedAppPanel.ts' />
///<reference path='AppManager.ts'/>
///<reference path='ServerEventsConnection.ts' />
///<reference path='ServerEventsListener.ts'/>