///<reference path='ModuleTreeGrid.ts'/>
///<reference path='InstallModuleAction.ts' />
///<reference path='StartModuleAction.ts' />
///<reference path='StopModuleAction.ts' />
///<reference path='UninstallModuleAction.ts' />
///<reference path='UpdateModuleAction.ts' />
///<reference path='ModuleBrowseActions.ts' />
///<reference path='StopModuleEvent.ts' />
///<reference path='StartModuleEvent.ts' />
///<reference path='UpdateModuleEvent.ts' />
///<reference path='UninstallModuleEvent.ts' />
///<reference path='InstallModuleDialog.ts' />
///<reference path='InstallModuleEvent.ts' />
///<reference path='ModuleBrowseItemsSelectionPanel.ts' />
///<reference path='ModuleBrowsePanel.ts' />
///<reference path='ModuleBrowseToolbar.ts' />

///<reference path='ModuleTreeGridContextMenu.ts'/>
///<reference path='ModuleBrowseItemPanel.ts'/>
