//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.xp.xml.model;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enonic.wem.api.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enonic.wem.api.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlRelationshipType }
     * 
     */
    public XmlRelationshipType createXmlRelationshipType() {
        return new XmlRelationshipType();
    }

    /**
     * Create an instance of {@link XmlLayoutDescriptor }
     * 
     */
    public XmlLayoutDescriptor createXmlLayoutDescriptor() {
        return new XmlLayoutDescriptor();
    }

    /**
     * Create an instance of {@link XmlMixin }
     * 
     */
    public XmlMixin createXmlMixin() {
        return new XmlMixin();
    }

    /**
     * Create an instance of {@link XmlPartDescriptor }
     * 
     */
    public XmlPartDescriptor createXmlPartDescriptor() {
        return new XmlPartDescriptor();
    }

    /**
     * Create an instance of {@link XmlImageDescriptor }
     * 
     */
    public XmlImageDescriptor createXmlImageDescriptor() {
        return new XmlImageDescriptor();
    }

    /**
     * Create an instance of {@link XmlPageDescriptor }
     * 
     */
    public XmlPageDescriptor createXmlPageDescriptor() {
        return new XmlPageDescriptor();
    }

    /**
     * Create an instance of {@link XmlModule }
     * 
     */
    public XmlModule createXmlModule() {
        return new XmlModule();
    }

    /**
     * Create an instance of {@link XmlContentType }
     * 
     */
    public XmlContentType createXmlContentType() {
        return new XmlContentType();
    }

    /**
     * Create an instance of {@link XmlFormItemSet }
     * 
     */
    public XmlFormItemSet createXmlFormItemSet() {
        return new XmlFormItemSet();
    }

    /**
     * Create an instance of {@link XmlMetadata }
     * 
     */
    public XmlMetadata createXmlMetadata() {
        return new XmlMetadata();
    }

    /**
     * Create an instance of {@link XmlRegionDescriptor }
     * 
     */
    public XmlRegionDescriptor createXmlRegionDescriptor() {
        return new XmlRegionDescriptor();
    }

    /**
     * Create an instance of {@link XmlRegions }
     * 
     */
    public XmlRegions createXmlRegions() {
        return new XmlRegions();
    }

    /**
     * Create an instance of {@link XmlFieldSet }
     * 
     */
    public XmlFieldSet createXmlFieldSet() {
        return new XmlFieldSet();
    }

    /**
     * Create an instance of {@link XmlOccurrence }
     * 
     */
    public XmlOccurrence createXmlOccurrence() {
        return new XmlOccurrence();
    }

    /**
     * Create an instance of {@link XmlInput }
     * 
     */
    public XmlInput createXmlInput() {
        return new XmlInput();
    }

    /**
     * Create an instance of {@link XmlForm }
     * 
     */
    public XmlForm createXmlForm() {
        return new XmlForm();
    }

    /**
     * Create an instance of {@link XmlFormItems }
     * 
     */
    public XmlFormItems createXmlFormItems() {
        return new XmlFormItems();
    }

    /**
     * Create an instance of {@link XmlInline }
     * 
     */
    public XmlInline createXmlInline() {
        return new XmlInline();
    }

    /**
     * Create an instance of {@link XmlVendor }
     * 
     */
    public XmlVendor createXmlVendor() {
        return new XmlVendor();
    }

    /**
     * Create an instance of {@link XmlMetaStep }
     * 
     */
    public XmlMetaStep createXmlMetaStep() {
        return new XmlMetaStep();
    }

    /**
     * Create an instance of {@link XmlRelationshipType.AllowedFromTypes }
     * 
     */
    public XmlRelationshipType.AllowedFromTypes createXmlRelationshipTypeAllowedFromTypes() {
        return new XmlRelationshipType.AllowedFromTypes();
    }

    /**
     * Create an instance of {@link XmlRelationshipType.AllowedToTypes }
     * 
     */
    public XmlRelationshipType.AllowedToTypes createXmlRelationshipTypeAllowedToTypes() {
        return new XmlRelationshipType.AllowedToTypes();
    }

    /**
     * Create an instance of {@link XmlLayoutComponentElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "layout-component")
    public XmlLayoutComponentElem createXmlLayoutComponentElem(XmlLayoutDescriptor value) {
        return new XmlLayoutComponentElem(value);
    }

    /**
     * Create an instance of {@link XmlMixinElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mixin")
    public XmlMixinElem createXmlMixinElem(XmlMixin value) {
        return new XmlMixinElem(value);
    }

    /**
     * Create an instance of {@link XmlPartComponentElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "part-component")
    public XmlPartComponentElem createXmlPartComponentElem(XmlPartDescriptor value) {
        return new XmlPartComponentElem(value);
    }

    /**
     * Create an instance of {@link XmlImageComponentElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image-component")
    public XmlImageComponentElem createXmlImageComponentElem(XmlImageDescriptor value) {
        return new XmlImageComponentElem(value);
    }

    /**
     * Create an instance of {@link XmlPageComponentElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "page-component")
    public XmlPageComponentElem createXmlPageComponentElem(XmlPageDescriptor value) {
        return new XmlPageComponentElem(value);
    }

    /**
     * Create an instance of {@link XmlModuleElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "module")
    public XmlModuleElem createXmlModuleElem(XmlModule value) {
        return new XmlModuleElem(value);
    }

    /**
     * Create an instance of {@link XmlContentTypeElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content-type")
    public XmlContentTypeElem createXmlContentTypeElem(XmlContentType value) {
        return new XmlContentTypeElem(value);
    }

    /**
     * Create an instance of {@link XmlRelationshipTypeElem }}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relationship-type")
    public XmlRelationshipTypeElem createXmlRelationshipTypeElem(XmlRelationshipType value) {
        return new XmlRelationshipTypeElem(value);
    }

}
