//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.xp.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class XmlPageComponentElem
    extends JAXBElement<XmlPageDescriptor>
{

    protected final static QName NAME = new QName("", "page-component");

    public XmlPageComponentElem(XmlPageDescriptor value) {
        super(NAME, ((Class) XmlPageDescriptor.class), null, value);
    }

    public XmlPageComponentElem() {
        super(NAME, ((Class) XmlPageDescriptor.class), null, null);
    }

}
