#auth.user =
#auth.password =
#auth.url
#auth.version =
#domain.id =
#domain.name =
#project.id =
#project.name =
#container =
readThrough.provider = file
readThrough.enabled = false
readThrough.sizeThreshold = 100mb