dependencies {
    implementation libs.osgi.core
    implementation libs.jspecify
    compileOnly libs.osgi.service.componentannotations
    api libs.im4j
    testImplementation libs.felix.framework
    testImplementation libs.felix.scr
    testImplementation libs.osgi.util.promise
    testImplementation libs.osgi.util.function
}

configurations {
    osgiTestBundles { transitive = false }
    im4jTestBundles { transitive = false }
}
dependencies {
    osgiTestBundles libs.felix.scr
    osgiTestBundles libs.osgi.service.component
    osgiTestBundles libs.osgi.service.cm
    osgiTestBundles libs.osgi.util.promise
    osgiTestBundles libs.osgi.util.function
    im4jTestBundles libs.im4j
    im4jTestBundles "com.enonic.im4j:im4j-natives-${gradle.ext.im4jHostPlatform()}:${libs.versions.im4j.get()}"
}

tasks.named( 'test' ) {
    testLogging.exceptionFormat = 'full'
    dependsOn tasks.named( 'jar' )
    doFirst {
        systemProperty 'imagemagick.bundle', tasks.named( 'jar' ).get().archiveFile.get().asFile.absolutePath
        systemProperty 'imagemagick.osgi.bundles', configurations.osgiTestBundles.asPath
        systemProperty 'imagemagick.im4j.bundles', configurations.im4jTestBundles.asPath
    }
}

jar {
    bundle {
        bnd( 'Bundle-Name': 'Enonic XP Core - ImageMagick' )
    }
}
