//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.xp.core.impl.export.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for indexConfigs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="indexConfigs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="analyzer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultConfig" type="{urn:enonic:xp:export:1.0}indexConfig"/>
 *         &lt;element name="pathIndexConfigs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pathIndexConfig" type="{urn:enonic:xp:export:1.0}pathIndexConfig" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "indexConfigs", propOrder = {
    "analyzer",
    "defaultConfig",
    "pathIndexConfigs"
})
public class XmlIndexConfigs {

    protected String analyzer;
    @XmlElement(required = true)
    protected XmlIndexConfig defaultConfig;
    protected XmlIndexConfigs.PathIndexConfigs pathIndexConfigs;

    /**
     * Gets the value of the analyzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalyzer() {
        return analyzer;
    }

    /**
     * Sets the value of the analyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalyzer(String value) {
        this.analyzer = value;
    }

    /**
     * Gets the value of the defaultConfig property.
     * 
     * @return
     *     possible object is
     *     {@link XmlIndexConfig }
     *     
     */
    public XmlIndexConfig getDefaultConfig() {
        return defaultConfig;
    }

    /**
     * Sets the value of the defaultConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlIndexConfig }
     *     
     */
    public void setDefaultConfig(XmlIndexConfig value) {
        this.defaultConfig = value;
    }

    /**
     * Gets the value of the pathIndexConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link XmlIndexConfigs.PathIndexConfigs }
     *     
     */
    public XmlIndexConfigs.PathIndexConfigs getPathIndexConfigs() {
        return pathIndexConfigs;
    }

    /**
     * Sets the value of the pathIndexConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlIndexConfigs.PathIndexConfigs }
     *     
     */
    public void setPathIndexConfigs(XmlIndexConfigs.PathIndexConfigs value) {
        this.pathIndexConfigs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pathIndexConfig" type="{urn:enonic:xp:export:1.0}pathIndexConfig" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pathIndexConfig"
    })
    public static class PathIndexConfigs {

        protected List<XmlPathIndexConfig> pathIndexConfig;

        /**
         * Gets the value of the pathIndexConfig property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pathIndexConfig property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPathIndexConfig().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlPathIndexConfig }
         * 
         * 
         */
        public List<XmlPathIndexConfig> getPathIndexConfig() {
            if (pathIndexConfig == null) {
                pathIndexConfig = new ArrayList<XmlPathIndexConfig>();
            }
            return this.pathIndexConfig;
        }

    }

}
