//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.xp.core.impl.export.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for node complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="node">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="childOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nodeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="data" type="{urn:enonic:xp:export:1.0}propertyTree"/>
 *         &lt;element name="indexConfigs" type="{urn:enonic:xp:export:1.0}indexConfigs" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "node", propOrder = {

})
public class XmlNode {

    protected String id;
    protected String childOrder;
    protected String nodeType;
    @XmlElement(required = true)
    protected XmlPropertyTree data;
    protected XmlIndexConfigs indexConfigs;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the childOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildOrder() {
        return childOrder;
    }

    /**
     * Sets the value of the childOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildOrder(String value) {
        this.childOrder = value;
    }

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeType(String value) {
        this.nodeType = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link XmlPropertyTree }
     *     
     */
    public XmlPropertyTree getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlPropertyTree }
     *     
     */
    public void setData(XmlPropertyTree value) {
        this.data = value;
    }

    /**
     * Gets the value of the indexConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link XmlIndexConfigs }
     *     
     */
    public XmlIndexConfigs getIndexConfigs() {
        return indexConfigs;
    }

    /**
     * Sets the value of the indexConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlIndexConfigs }
     *     
     */
    public void setIndexConfigs(XmlIndexConfigs value) {
        this.indexConfigs = value;
    }

}
