//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.xp.core.impl.export.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class XmlNodeElem
    extends JAXBElement<XmlNode>
{

    protected final static QName NAME = new QName("urn:enonic:xp:export:1.0", "node");

    public XmlNodeElem(XmlNode value) {
        super(NAME, ((Class) XmlNode.class), null, value);
    }

    public XmlNodeElem() {
        super(NAME, ((Class) XmlNode.class), null, null);
    }

}
