//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:12:54 PM CET 
//


package com.enonic.xp.core.impl.export.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertyTree complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertyTree">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="localDateTime" type="{urn:enonic:xp:export:1.0}localDateTimeProperty"/>
 *           &lt;element name="string" type="{urn:enonic:xp:export:1.0}stringProperty"/>
 *           &lt;element name="double" type="{urn:enonic:xp:export:1.0}doubleProperty"/>
 *           &lt;element name="long" type="{urn:enonic:xp:export:1.0}longProperty"/>
 *           &lt;element name="geoPoint" type="{urn:enonic:xp:export:1.0}geoPointProperty"/>
 *           &lt;element name="boolean" type="{urn:enonic:xp:export:1.0}booleanProperty"/>
 *           &lt;element name="dateTime" type="{urn:enonic:xp:export:1.0}dateTimeProperty"/>
 *           &lt;element name="localDate" type="{urn:enonic:xp:export:1.0}dateProperty"/>
 *           &lt;element name="localTime" type="{urn:enonic:xp:export:1.0}timeProperty"/>
 *           &lt;element name="binaryReference" type="{urn:enonic:xp:export:1.0}binaryReferenceProperty"/>
 *           &lt;element name="reference" type="{urn:enonic:xp:export:1.0}referenceProperty"/>
 *           &lt;element name="link" type="{urn:enonic:xp:export:1.0}linkProperty"/>
 *           &lt;element name="htmlPart" type="{urn:enonic:xp:export:1.0}htmlPartProperty"/>
 *           &lt;element name="xml" type="{urn:enonic:xp:export:1.0}xmlProperty"/>
 *           &lt;element name="property-set" type="{urn:enonic:xp:export:1.0}propertySet"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertyTree", propOrder = {
    "list"
})
@XmlSeeAlso({
    XmlPropertySet.class
})
public class XmlPropertyTree {

    @XmlElements({
        @XmlElement(name = "localDateTime", type = XmlLocalDateTimeProperty.class),
        @XmlElement(name = "string", type = XmlStringProperty.class),
        @XmlElement(name = "double", type = XmlDoubleProperty.class),
        @XmlElement(name = "long", type = XmlLongProperty.class),
        @XmlElement(name = "geoPoint", type = XmlGeoPointProperty.class),
        @XmlElement(name = "boolean", type = XmlBooleanProperty.class),
        @XmlElement(name = "dateTime", type = XmlDateTimeProperty.class),
        @XmlElement(name = "localDate", type = XmlDateProperty.class),
        @XmlElement(name = "localTime", type = XmlTimeProperty.class),
        @XmlElement(name = "binaryReference", type = XmlBinaryReferenceProperty.class),
        @XmlElement(name = "reference", type = XmlReferenceProperty.class),
        @XmlElement(name = "link", type = XmlLinkProperty.class),
        @XmlElement(name = "htmlPart", type = XmlHtmlPartProperty.class),
        @XmlElement(name = "xml", type = XmlXmlProperty.class),
        @XmlElement(name = "property-set", type = XmlPropertySet.class)
    })
    protected List<Object> list;

    /**
     * Gets the value of the list property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlLocalDateTimeProperty }
     * {@link XmlStringProperty }
     * {@link XmlDoubleProperty }
     * {@link XmlLongProperty }
     * {@link XmlGeoPointProperty }
     * {@link XmlBooleanProperty }
     * {@link XmlDateTimeProperty }
     * {@link XmlDateProperty }
     * {@link XmlTimeProperty }
     * {@link XmlBinaryReferenceProperty }
     * {@link XmlReferenceProperty }
     * {@link XmlLinkProperty }
     * {@link XmlHtmlPartProperty }
     * {@link XmlXmlProperty }
     * {@link XmlPropertySet }
     * 
     * 
     */
    public List<Object> getList() {
        if (list == null) {
            list = new ArrayList<Object>();
        }
        return this.list;
    }

}
