//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 09:37:12 PM CET 
//


package com.enonic.wem.export.internal.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pathIndexConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pathIndexConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indexConfig" type="{urn:enonic:xp:export:1.0}indexConfig"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pathIndexConfig", propOrder = {
    "indexConfig",
    "path"
})
public class XmlPathIndexConfig {

    @XmlElement(required = true)
    protected XmlIndexConfig indexConfig;
    @XmlElement(required = true)
    protected String path;

    /**
     * Gets the value of the indexConfig property.
     * 
     * @return
     *     possible object is
     *     {@link XmlIndexConfig }
     *     
     */
    public XmlIndexConfig getIndexConfig() {
        return indexConfig;
    }

    /**
     * Sets the value of the indexConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlIndexConfig }
     *     
     */
    public void setIndexConfig(XmlIndexConfig value) {
        this.indexConfig = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
